const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('api', {
  login: (id, password) => ipcRenderer.invoke('auth-sign-in', { id, password }),

  getSections: () => ipcRenderer.invoke('get-sections'),
  getAgeGroups: (sectionCode) => ipcRenderer.invoke('get-age-groups', sectionCode),
  getCategories: () => ipcRenderer.invoke('get-categories'),
  getCategoriesForSection: (sectionCode) => ipcRenderer.invoke('get-categories-for-section', sectionCode),
  getProteinTypes: () => ipcRenderer.invoke('get-protein-types'),
  refreshReferenceData: () => ipcRenderer.invoke('refresh-reference-data'),

  getItems: (sectionCode) => ipcRenderer.invoke('get-items', sectionCode),
  getItemPortions: (itemId) => ipcRenderer.invoke('get-item-portions', itemId),
  suggestClassification: (payload) => ipcRenderer.invoke('suggest-classification', payload),
  addItem: (payload) => ipcRenderer.invoke('add-item', payload),
  updateItem: (payload) => ipcRenderer.invoke('update-item', payload),
  updateItemRc: (payload) => ipcRenderer.invoke('update-item-rc', payload),
  deleteItem: (itemId) => ipcRenderer.invoke('delete-item', itemId),

  searchIngredients: (query) => ipcRenderer.invoke('search-ingredients', query),
  addIngredient: (payload) => ipcRenderer.invoke('add-ingredient', payload),
  updateIngredient: (payload) => ipcRenderer.invoke('update-ingredient', payload),
  listIngredients: () => ipcRenderer.invoke('list-ingredients'),
  deleteIngredient: (id) => ipcRenderer.invoke('delete-ingredient', id),
  listRecipes: () => ipcRenderer.invoke('list-recipes'),
  searchRecipes: (query) => ipcRenderer.invoke('search-recipes', query),
  getRecipe: (id) => ipcRenderer.invoke('get-recipe', id),
  saveRecipe: (payload) => ipcRenderer.invoke('save-recipe', payload),
  deleteRecipe: (id) => ipcRenderer.invoke('delete-recipe', id),
  getRecipePhoto: (photoPath) => ipcRenderer.invoke('get-recipe-photo', photoPath),
  exportRecipes: (payload) => ipcRenderer.invoke('export-recipes', payload),
  exportScaledRecipe: (payload) => ipcRenderer.invoke('export-scaled-recipe', payload),

  searchExtractedIngredients: (query) => ipcRenderer.invoke('search-extracted-ingredients', query),
  addExtractedIngredient: (payload) => ipcRenderer.invoke('add-extracted-ingredient', payload),
  listExtractedRecipes: () => ipcRenderer.invoke('list-extracted-recipes'),
  getExtractedRecipe: (id) => ipcRenderer.invoke('get-extracted-recipe', id),
  saveExtractedRecipe: (payload) => ipcRenderer.invoke('save-extracted-recipe', payload),
  deleteExtractedRecipe: (id) => ipcRenderer.invoke('delete-extracted-recipe', id),
  getExtractedRecipePhoto: (photoPath) => ipcRenderer.invoke('get-extracted-recipe-photo', photoPath),
  exportExtractedRecipes: (payload) => ipcRenderer.invoke('export-extracted-recipes', payload),
  extractRecipeForExtractor: (payload) => ipcRenderer.invoke('extract-recipe-for-extractor', payload),

  generateMenu: (payload) => ipcRenderer.invoke('generate-menu', payload),
  listGeneratedMenus: () => ipcRenderer.invoke('list-generated-menus'),
  getLatestGeneratedMenu: (sectionCode) => ipcRenderer.invoke('get-latest-generated-menu', sectionCode),
  getGeneratedMenuDetail: (id) => ipcRenderer.invoke('get-generated-menu-detail', id),
  deleteGeneratedMenus: (menuIds) => ipcRenderer.invoke('delete-generated-menus', menuIds),
  swapMenuItem: (payload) => ipcRenderer.invoke('swap-menu-item', payload),
  getEligibleSwapItems: (payload) => ipcRenderer.invoke('get-eligible-swap-items', payload),

  exportMenuToExcel: (payload) => ipcRenderer.invoke('export-menu-to-excel', payload),
  exportAllSectionsToExcel: (payload) => ipcRenderer.invoke('export-all-sections-to-excel', payload),
  generateAndExportAll: (payload) => ipcRenderer.invoke('generate-and-export-all', payload),

  getSectionSlots: (sectionCode) => ipcRenderer.invoke('get-section-slots', sectionCode),
  getSchoolDays: (payload) => ipcRenderer.invoke('get-school-days', payload),
  getSectionItemPool: (sectionCode) => ipcRenderer.invoke('get-section-item-pool', sectionCode),
  builderFillSuggestions: (payload) => ipcRenderer.invoke('builder-fill-suggestions', payload),
  saveManualMenu: (payload) => ipcRenderer.invoke('save-manual-menu', payload),
  exportBlankTemplate: (payload) => ipcRenderer.invoke('export-blank-template', payload),
});
