// ============================================================
// AI Menu Generator: the AI invents dishes, the EXISTING rule engine (lib/generator.js) builds the
// menu from them. This module holds the feature's fixed scope and runs the engine over AI-made
// draft pools, entirely in memory -- nothing here reads or writes the draft tables or the AI.
//
// How a draft run works: for each section, the categories in AI_CATEGORIES get a pool of draft
// dishes (draftDishToPoolItem) instead of the catalog pool; every other category (Milk, Fruit Bar,
// Bread, Juice, Staff salads/sweets/bread, ...) is picked from the real catalog exactly as today.
// Sections run in DRAFT_SECTION_ORDER and share their picks through one in-memory partnerPicks
// object, so the KG-LP/MS-UP coupling and Staff's Main/Breakfast shares see this run's picks
// instead of looking for saved generated_menus rows (a draft isn't saved anywhere yet). CEO is
// never part of a draft; it is generated by the unchanged engine at Approve time.
// ============================================================
const { MenuGenerator, SECTION_SLOTS } = require('./generator');
const { getProteinByCode } = require('./referenceData');
const { cuisineForDate } = require('./nationalDay');

// Confirmed with the chef 2026-09-23 (Staff Sweets added the same day). Anything not listed stays on
// the catalog, unchanged.
const AI_CATEGORIES = {
  DAYCARE: ['AM_SNACK', 'LUNCH_MAIN', 'LUNCH_SALAD', 'SOUP_APPETIZER', 'PM_SNACK'],
  KG_LP: ['AM_SNACK', 'LUNCH_MAIN', 'LUNCH_STARCH', 'SOUP_APPETIZER', 'PM_SNACK'],
  MS_UP: ['AM_SNACK', 'LUNCH_MAIN', 'LUNCH_VEGETABLE', 'LUNCH_STARCH', 'SOUP_APPETIZER', 'PM_SNACK'],
  // STAFF_SWEETS moved to AI 2026-09-23 (was catalog-only in the Phase 0 decision).
  STAFF: ['STAFF_BREAKFAST', 'STAFF_APPETIZER', 'STAFF_MAIN', 'STAFF_SWEETS', 'STAFF_LUNCHBOX'],
};

// Student sections first (Staff shares their Lunch Main and AM Snack picks), KG-LP before MS-UP
// (MS-UP copies KG-LP's coupled Lunch Main/Starch) -- same order as generate-and-export-all.
const DRAFT_SECTION_ORDER = ['DAYCARE', 'KG_LP', 'MS_UP', 'STAFF'];

for (const [sectionCode, cats] of Object.entries(AI_CATEGORIES)) {
  const slotCats = new Set(SECTION_SLOTS[sectionCode].map(([c]) => c));
  for (const c of cats) {
    if (!slotCats.has(c)) throw new Error(`aiMenu: ${sectionCode} has no ${c} slot in SECTION_SLOTS`);
  }
}

function isAiCategory(sectionCode, categoryCode) {
  return (AI_CATEGORIES[sectionCode] || []).includes(categoryCode);
}

// A draft dish row (ai_menu_draft_dishes shape) -> the item shape _pickItems scores. A dish linked
// to an existing catalog item uses that item's REAL id, so the engine checks it against real
// served history like any other catalog item; a new dish gets a 'd:<id>' id that can never
// collide with a numeric menu_items id.
function draftDishToPoolItem(dish) {
  const protein = dish.protein_code ? getProteinByCode(dish.protein_code) : null;
  const linked = dish.resolution === 'link' && dish.dup_match_item_id;
  return {
    id: linked ? dish.dup_match_item_id : `d:${dish.id}`,
    draftDishId: dish.id,
    name: dish.name,
    protein_type_id: protein ? protein.id : null,
    is_daily_repeating: 0,
    sauce_type: dish.sauce_type || null,
    carb_type: dish.carb_type || null,
    dish_concept: dish.dish_concept || null,
    am_snack_style: dish.am_snack_style || null,
    // National Day: set on dishes made for one Tuesday's cuisine (the engine keeps them for it).
    cuisine: dish.cuisine || null,
    category_id: null,
    is_active: 1,
  };
}

// draftPools: { [sectionCode]: { [categoryCode]: [poolItem, ...] } }. Returns, per section, the
// engine's resultDays (items: { category, id, name, draftDishId? }) and its warnings. Read-only
// against Supabase (catalog pools for the unchanged categories, served history); writes nothing.
async function computeDraftMenus({ startDate, numWeekdays, draftPools }) {
  const partnerPicks = {};
  const bySection = {};

  for (const sectionCode of DRAFT_SECTION_ORDER) {
    const pools = (draftPools && draftPools[sectionCode]) || {};
    const gen = new MenuGenerator({ draftPools: pools, partnerPicks, dayTheme: cuisineForDate });
    const { resultDays, warnings } = await gen.computeMenu(sectionCode, new Date(startDate), numWeekdays);

    // Full item rows (not just ids) go into partnerPicks: Staff's forced shares add their
    // protein / dish_concept to the slot's rules, same as with rows loaded from the DB.
    const itemsById = new Map();
    for (const list of Object.values(pools)) for (const it of list) itemsById.set(it.id, it);
    for (const list of (gen._itemPoolCache ? gen._itemPoolCache.values() : [])) {
      for (const it of list) if (!itemsById.has(it.id)) itemsById.set(it.id, it);
    }
    for (const byDate of Object.values(partnerPicks)) {
      for (const byCat of Object.values(byDate)) {
        for (const list of Object.values(byCat)) for (const it of list) if (!itemsById.has(it.id)) itemsById.set(it.id, it);
      }
    }

    const picksByDate = {};
    for (const day of resultDays) {
      const byCat = (picksByDate[day.date] = {});
      for (const it of day.items) {
        const full = itemsById.get(it.id) || { id: it.id, name: it.name };
        (byCat[it.category] = byCat[it.category] || []).push(full);
        if (full.draftDishId) it.draftDishId = full.draftDishId;
      }
    }
    partnerPicks[sectionCode] = picksByDate;
    bySection[sectionCode] = { resultDays, warnings };
  }
  return bySection;
}

module.exports = { AI_CATEGORIES, DRAFT_SECTION_ORDER, isAiCategory, draftDishToPoolItem, computeDraftMenus };
