// ============================================================
// AI Menu Generator, Phase 4: Approve -- the one step where AI-generated content becomes permanent
// (new Dish Catalog items, saved menus in History). Everything before this only touched the
// ai_menu_* draft tables.
//
// Safe to interrupt at any point, using this app's idempotent-step convention (each step only
// touches rows its marker says are still undone, so running it again finishes the job):
//   1. Claim: draft -> approving by compare-and-swap (only one of two people clicking wins), with
//      a claim token and a heartbeat (approve_claimed_at) refreshed after every step. A run whose
//      heartbeat went quiet (STALE_MS) was interrupted and can be resumed -- again by CAS.
//   2. Re-check BEFORE any permanent write: no empty slots, every served dish passes the full
//      safety check again (hard block), and the catalog duplicate check is re-run (a dish that now
//      matches a retired catalog item blocks). A failure hands the run back as a draft.
//   3. Dishes -> catalog items: a new dish becomes a menu_items row (is_ai_generated,
//      ai_menu_run_id); a linked one uses its catalog item. The marker is
//      ai_menu_draft_dishes.resolved_item_id, set right after each dish, and a unique-name clash on
//      insert (the item was made by an interrupted earlier try, or by someone else meanwhile) is
//      resolved by linking to that row, so nothing is ever created twice.
//   4. Portions: item_portions for every served section whose menu actually has the dish's category
//      -- only the missing rows, so a linked catalog item newly served in another section gets that
//      section. Shared copies (a school Lunch Main inside Staff Main) don't make the dish a Staff
//      catalog item, exactly as with the regular engine.
//   5. Menus: each section saved with the existing persistMenu under the run's batch id; recorded
//      in approve_progress, and a section half-saved by an interrupted try is deleted and saved
//      again. Then CEO is generated by the UNCHANGED engine into the same batch.
//   6. approved.
// ============================================================
const crypto = require('crypto');
const { supabase, supaFail } = require('./supabaseClient');
const { MenuGenerator, SECTION_SLOTS } = require('./generator');
const { DRAFT_SECTION_ORDER } = require('./aiMenu');
const { getCategoryByCode, getSectionByCode, getAgeGroupsForSection, getProteinByCode, getCategoryPortionDefault } = require('./referenceData');
const { findDuplicateMatch, emptyDishIndex, addNameToIndex, normalizeDishName } = require('./recipeGenerator');
const { checkDishSafety } = require('./aiMenuSafety');

// No step takes anywhere near this long; a claim older than this was interrupted.
const STALE_MS = 3 * 60 * 1000;
const RUN_COLUMNS = 'id, label, created_by, start_date, end_date, num_weekdays, status, batch_id, approve_claim, approve_claimed_at, approve_progress, approved_by, approved_at';

async function fetchAll(buildQuery, context) {
  const all = [];
  for (let from = 0; ; from += 1000) {
    const { data, error } = await buildQuery().range(from, from + 999);
    if (error) throw supaFail(context, error);
    all.push(...data);
    if (data.length < 1000) return all;
  }
}

function sectionsServingCategory(categoryCode) {
  return DRAFT_SECTION_ORDER.filter((s) => SECTION_SLOTS[s].some(([c]) => c === categoryCode));
}

async function loadRun(runId) {
  const { data, error } = await supabase.from('ai_menu_runs').select(RUN_COLUMNS).eq('id', runId).single();
  if (error) {
    if (/approve_claim|approve_progress/.test(error.message || '')) {
      throw new Error('Approve needs the 20260924120000_ai_menu_approve.sql migration -- run it in the Supabase SQL editor first.');
    }
    throw supaFail('aiMenuApprove: load run', error);
  }
  return data;
}

// ---------- claim ----------

async function claim(run, by) {
  const token = crypto.randomUUID();
  const now = new Date().toISOString();
  let q;
  if (run.status === 'draft') {
    q = supabase.from('ai_menu_runs').update({
      status: 'approving', approve_claim: token, approve_claimed_at: now, approved_by: by || null,
      batch_id: run.batch_id || crypto.randomUUID(),
    }).eq('id', run.id).eq('status', 'draft');
  } else if (run.status === 'approving') {
    const last = run.approve_claimed_at ? new Date(run.approve_claimed_at).getTime() : 0;
    if (Date.now() - last < STALE_MS) {
      throw new Error(`${run.approved_by || 'Someone'} is approving this menu right now -- try again in a few minutes if it doesn't finish.`);
    }
    q = supabase.from('ai_menu_runs').update({ approve_claim: token, approve_claimed_at: now, approved_by: by || run.approved_by })
      .eq('id', run.id).eq('status', 'approving');
    q = run.approve_claim ? q.eq('approve_claim', run.approve_claim) : q.is('approve_claim', null);
  } else {
    throw new Error(`This run is ${run.status} -- only a draft can be approved.`);
  }
  const { data, error } = await q.select(RUN_COLUMNS);
  if (error) throw supaFail('aiMenuApprove: claim', error);
  if (!data.length) throw new Error('Someone else started approving this menu at the same moment -- it is theirs now.');
  return { token, run: data[0] };
}

// Refreshes the heartbeat; fails if another person took the run over.
async function heartbeat(runId, token, extra = {}) {
  const { data, error } = await supabase.from('ai_menu_runs')
    .update({ approve_claimed_at: new Date().toISOString(), ...extra })
    .eq('id', runId).eq('approve_claim', token).select('id');
  if (error) throw supaFail('aiMenuApprove: heartbeat', error);
  if (!data.length) throw new Error('This approval was taken over by someone else (it had gone quiet); nothing more was written from here.');
}

async function release(runId, token) {
  await supabase.from('ai_menu_runs').update({ status: 'draft', approve_claim: null, approve_claimed_at: null, approved_by: null })
    .eq('id', runId).eq('approve_claim', token);
}

// ---------- catalog helpers ----------

async function catalogIndexFor(categoryCode) {
  const category = getCategoryByCode(categoryCode);
  const rows = await fetchAll(() => supabase.from('menu_items').select('id, name, is_active').eq('category_id', category.id).order('id'),
    'aiMenuApprove: load catalog');
  const index = emptyDishIndex();
  const byNorm = new Map();
  for (const r of rows) {
    addNameToIndex(index, r.name);
    const k = normalizeDishName(r.name);
    if (!byNorm.has(k) || (r.is_active && !byNorm.get(k).is_active)) byNorm.set(k, r);
  }
  return { match: (name) => { const m = findDuplicateMatch(name, index); return m ? { item: byNorm.get(normalizeDishName(m.matchedName)), matchType: m.matchType } : null; } };
}

async function ensurePortions(itemId, categoryCode, sectionCodes) {
  const category = getCategoryByCode(categoryCode);
  const serve = sectionCodes.filter((s) => sectionsServingCategory(categoryCode).includes(s));
  const ageGroups = serve.flatMap((s) => getAgeGroupsForSection(getSectionByCode(s).id));
  if (!ageGroups.length) return 0;
  const { data: existing, error } = await supabase.from('item_portions').select('age_group_id').eq('item_id', itemId);
  if (error) throw supaFail('aiMenuApprove: load item_portions', error);
  const have = new Set(existing.map((r) => r.age_group_id));
  const rows = ageGroups.filter((ag) => !have.has(ag.id)).map((ag) => {
    const def = getCategoryPortionDefault(category.id, ag.section_id);
    return { item_id: itemId, age_group_id: ag.id, unit: def?.unit || 'n/a', price: null };
  });
  if (rows.length) {
    const { error: insErr } = await supabase.from('item_portions').insert(rows);
    if (insErr && insErr.code !== '23505') throw supaFail('aiMenuApprove: insert item_portions', insErr);
  }
  return rows.length;
}

async function deleteMenus(menuIds) {
  if (!menuIds.length) return;
  const { data: days, error } = await supabase.from('menu_days').select('id').in('generated_menu_id', menuIds);
  if (error) throw supaFail('aiMenuApprove: load menu_days', error);
  if (days.length) {
    const { error: e1 } = await supabase.from('menu_day_items').delete().in('menu_day_id', days.map((d) => d.id));
    if (e1) throw supaFail('aiMenuApprove: delete menu_day_items', e1);
  }
  const { error: e2 } = await supabase.from('menu_days').delete().in('generated_menu_id', menuIds);
  if (e2) throw supaFail('aiMenuApprove: delete menu_days', e2);
  const { error: e3 } = await supabase.from('generated_menus').delete().in('id', menuIds);
  if (e3) throw supaFail('aiMenuApprove: delete generated_menus', e3);
}

// ---------- approve ----------

// Returns { ok: true, menuIdsBySection, created, linked, portionsAdded, ceoWarnings } or
// { ok: false, blocked: { emptySlots, safety: [...], retired: [...] } } (the run is a draft again).
async function approveRun({ runId, approvedBy, onProgress = () => {} }) {
  let run = await loadRun(runId);
  if (run.status === 'approved') return { ok: true, alreadyApproved: true, menuIdsBySection: run.approve_progress?.sections || {} };
  const resuming = run.status === 'approving';
  onProgress(resuming ? 'Resuming the interrupted approval...' : 'Checking the menu before saving anything...');
  const claimed = await claim(run, approvedBy);
  const { token } = claimed;
  run = claimed.run;
  const progress = { sections: { ...(run.approve_progress?.sections || {}) } };

  const [dishes, picks] = await Promise.all([
    fetchAll(() => supabase.from('ai_menu_draft_dishes').select('*').eq('run_id', runId).order('id'), 'aiMenuApprove: load dishes'),
    fetchAll(() => supabase.from('ai_menu_draft_picks').select('*').eq('run_id', runId).order('id'), 'aiMenuApprove: load picks'),
  ]);
  const dishById = new Map(dishes.map((d) => [d.id, d]));
  const servedIds = [...new Set(picks.filter((p) => p.draft_dish_id).map((p) => p.draft_dish_id))];
  const served = servedIds.map((id) => dishById.get(id)).filter(Boolean);

  // 2. Re-check before any permanent write.
  const emptySlots = picks.filter((p) => !p.draft_dish_id && !p.item_id).length;
  const safety = [];
  for (const d of served) {
    const r = checkDishSafety(d);
    if (!r.ok) safety.push({ dishId: d.id, name: d.name, category: d.category_code, reason: r.reason });
  }
  const retired = [];
  const indexes = new Map();
  for (const d of served.filter((x) => !x.resolved_item_id && x.resolution === 'new')) {
    if (!indexes.has(d.category_code)) indexes.set(d.category_code, await catalogIndexFor(d.category_code));
    const m = indexes.get(d.category_code).match(d.name);
    if (m && m.item && !m.item.is_active) retired.push({ dishId: d.id, name: d.name, matched: m.item.name });
  }
  if (emptySlots || safety.length || retired.length) {
    const nothingWritten = !served.some((d) => d.resolved_item_id) && !Object.keys(progress.sections).length;
    if (nothingWritten) await release(runId, token);
    return { ok: false, handedBack: nothingWritten, blocked: { emptySlots, safety, retired } };
  }
  await heartbeat(runId, token);

  // 3 + 4. Dishes -> catalog items, and their portions.
  let created = 0, linked = 0, portionsAdded = 0;
  const vegan = getProteinByCode('VEGAN');
  for (let i = 0; i < served.length; i++) {
    const d = served[i];
    if (i % 20 === 0) { onProgress(`Adding dishes to the Dish Catalog: ${i} of ${served.length}...`); await heartbeat(runId, token); }
    let itemId = d.resolved_item_id;
    if (!itemId && d.resolution === 'link' && d.dup_match_item_id) {
      itemId = d.dup_match_item_id;
      linked++;
    }
    if (!itemId) {
      if (!indexes.has(d.category_code)) indexes.set(d.category_code, await catalogIndexFor(d.category_code));
      const m = indexes.get(d.category_code).match(d.name);
      if (m && m.item && m.item.is_active) {
        itemId = m.item.id; // created meanwhile (by someone, or an interrupted earlier try)
        linked++;
      } else {
        const protein = d.protein_code ? getProteinByCode(d.protein_code) : null;
        if (d.protein_code && !protein) throw new Error(`Unknown protein type ${d.protein_code} on "${d.name}"${d.protein_code === 'VEGAN' && !vegan ? ' -- the VEGAN migration has not been run' : ''}.`);
        const { data: ins, error: insErr } = await supabase.from('menu_items').insert({
          name: d.name, category_id: getCategoryByCode(d.category_code).id, protein_type_id: protein ? protein.id : null,
          is_daily_repeating: 0, sauce_type: d.sauce_type, carb_type: d.carb_type, dish_concept: d.dish_concept,
          am_snack_style: d.am_snack_style, calories_per_100g: null, is_active: 1, created_at: new Date().toISOString(),
          is_ai_generated: true, ai_menu_run_id: runId,
        }).select('id').single();
        if (insErr && insErr.code === '23505') {
          const { data: existing, error: exErr } = await supabase.from('menu_items').select('id')
            .eq('name', d.name).eq('category_id', getCategoryByCode(d.category_code).id).limit(1);
          if (exErr || !existing.length) throw supaFail('aiMenuApprove: find existing item after name clash', exErr || insErr);
          itemId = existing[0].id;
          linked++;
        } else if (insErr) {
          throw supaFail(`aiMenuApprove: create "${d.name}"`, insErr);
        } else {
          itemId = ins.id;
          created++;
        }
      }
    }
    const { error: markErr } = await supabase.from('ai_menu_draft_dishes').update({ resolved_item_id: itemId }).eq('id', d.id);
    if (markErr) throw supaFail('aiMenuApprove: mark dish resolved', markErr);
    d.resolved_item_id = itemId;
    portionsAdded += await ensurePortions(itemId, d.category_code, d.section_codes);
  }

  // 5. Menus, then CEO -- one batch.
  const batchId = run.batch_id;
  const label = run.label;
  const createdBy = run.created_by || approvedBy || null;
  const startDate = new Date(run.start_date);
  const { data: batchMenus, error: bmErr } = await supabase.from('generated_menus').select('id, section_id').eq('batch_id', batchId);
  if (bmErr) throw supaFail('aiMenuApprove: load batch menus', bmErr);
  const recorded = new Set(Object.values(progress.sections));
  // Anything in the batch not recorded as finished is a section an interrupted try half-saved.
  await deleteMenus(batchMenus.filter((m) => !recorded.has(m.id)).map((m) => m.id));

  for (const section of DRAFT_SECTION_ORDER) {
    if (progress.sections[section]) continue;
    onProgress(`Saving the ${section.replace('_', '-')} menu...`);
    const byDate = new Map();
    for (const p of picks.filter((x) => x.section_code === section).sort((a, b) => a.slot_index - b.slot_index)) {
      if (!byDate.has(p.menu_date)) byDate.set(p.menu_date, { date: p.menu_date, weekday: p.weekday, items: [] });
      const id = p.draft_dish_id ? dishById.get(p.draft_dish_id)?.resolved_item_id : p.item_id;
      if (!id) throw new Error(`A ${section} ${p.category_code} slot on ${p.menu_date} has no dish -- nothing saved for ${section}.`);
      byDate.get(p.menu_date).items.push({ category: p.category_code, id });
    }
    const resultDays = [...byDate.values()].sort((a, b) => a.date.localeCompare(b.date));
    const menuId = await new MenuGenerator().persistMenu(section, label, startDate, resultDays, batchId, createdBy);
    progress.sections[section] = menuId;
    await heartbeat(runId, token, { approve_progress: progress });
  }

  let ceoWarnings = [];
  if (!progress.sections.CEO) {
    onProgress('Generating the CEO menu (unchanged engine)...');
    const gen = new MenuGenerator();
    const { menuId } = await gen.generate('CEO', label, startDate, run.num_weekdays, batchId, createdBy);
    ceoWarnings = gen.warnings;
    progress.sections.CEO = menuId;
    await heartbeat(runId, token, { approve_progress: progress });
  }

  // 6. Done.
  const { data: fin, error: finErr } = await supabase.from('ai_menu_runs').update({
    status: 'approved', approved_at: new Date().toISOString(), approve_claim: null, approve_claimed_at: null, approve_progress: progress,
  }).eq('id', runId).eq('approve_claim', token).select('id');
  if (finErr) throw supaFail('aiMenuApprove: finish', finErr);
  if (!fin.length) throw new Error('This approval was taken over by someone else before it finished.');
  onProgress('Approved.');
  return { ok: true, menuIdsBySection: progress.sections, created, linked, portionsAdded, ceoWarnings, resumed: resuming };
}

module.exports = { approveRun, STALE_MS, sectionsServingCategory };
