-- AI Menu Generator, Phase 0: schema only. Run 20260923090000_ai_menu_generator_preflight.sql
-- first (read-only) and check its output against the value lists below.
--
-- Lifecycle: a run is generated into the three draft tables below, reviewed and edited by the chef
-- on the AI Menu Generator screen, and only on Approve does anything reach the real tables
-- (menu_items / item_portions for each new dish, then generated_menus / menu_days /
-- menu_day_items through the existing persistMenu, with CEO generated by the unchanged engine
-- in the same batch). Drafts never go into generated_menus: the no-repeat history and the
-- cross-section sharing lookups read every generated_menus row regardless of status, so an
-- unapproved draft there would count as "served".
--
-- Purely ADDITIVE: two nullable/defaulted columns on menu_items and three new tables. Nothing
-- existing changes behaviour; Generate Menu / Build Menu / Export All ignore all of it.

begin;

-- ------------------------------------------------------------------
-- 1. One row per AI generation run.
-- ------------------------------------------------------------------
create table public.ai_menu_runs (
  id bigint generated by default as identity primary key,
  label text not null,
  created_by text,
  start_date date not null,
  end_date date not null check (end_date >= start_date),
  num_weekdays integer not null check (num_weekdays > 0),
  -- generating: the AI calls are still filling the drafts (a run left here crashed mid-way).
  -- draft: ready for review. approving: claimed by one Approve click (the app moves draft ->
  -- approving with a conditional update, so two people can't approve the same run twice; the
  -- owner and chefs use the app at the same time). approved / discarded: final.
  status text not null default 'generating'
    check (status in ('generating', 'draft', 'approving', 'approved', 'discarded')),
  -- Generation-time notes shown in the review panel: repeat-rule warnings, composition rules
  -- that couldn't be met, and every dish the nut/sesame/seafood check rejected (never silent).
  warnings jsonb not null default '[]'::jsonb,
  -- Set on Approve: the generated_menus.batch_id shared by the 5 saved sections.
  batch_id uuid,
  created_at timestamptz not null default now(),
  approved_at timestamptz,
  approved_by text
);

create index ai_menu_runs_status_idx on public.ai_menu_runs (status);

-- ------------------------------------------------------------------
-- 2. One row per DISTINCT dish in a run (a dish served on several days, or shared by several
--    sections, is one row), so the chef reviews each dish once.
-- ------------------------------------------------------------------
create table public.ai_menu_draft_dishes (
  id bigint generated by default as identity primary key,
  run_id bigint not null references public.ai_menu_runs (id) on delete cascade,
  name text not null check (length(btrim(name)) > 0),
  category_code text not null,
  -- Sections this dish is available to (becomes its item_portions rows on Approve). CEO is never
  -- part of this feature.
  section_codes text[] not null
    check (cardinality(section_codes) > 0
       and section_codes <@ array['DAYCARE', 'KG_LP', 'MS_UP', 'STAFF']::text[]),
  -- Attributes the existing rule engine reads (composition, distinct sauce/carb/concept, the AM
  -- Snack Pastry/Cold-Kitchen rotation). protein_code is checked in code against protein_types.
  protein_code text,
  sauce_type text check (sauce_type in ('RED', 'WHITE', 'ASIAN', 'GLAZED', 'GRAVY', 'DRY')),
  carb_type text check (carb_type in ('RICE', 'PASTA', 'POTATO', 'OTHER')),
  dish_concept text check (dish_concept in ('EGG', 'PASTRY', 'SANDWICH', 'CEREAL_DAIRY', 'CHEESE', 'OTHER')),
  am_snack_style text check (am_snack_style in ('PASTRY', 'COLD_KITCHEN')),
  description text,
  -- Required, never empty: the nut/sesame (and, for student sections, seafood) check scans these
  -- as well as the name, and a known-risk dish (hummus, pesto, baklava...) must state its
  -- nut/sesame-free substitution here explicitly.
  key_ingredients text[] not null check (cardinality(key_ingredients) > 0),
  -- Result of the last code-level safety check (terms checked, when, against which name/ingredients).
  -- A dish that fails is rejected and never stored, so every stored row passed.
  safety_scan jsonb not null default '{}'::jsonb,
  -- Duplicate check against the real Dish Catalog (findDuplicateMatch, same category only).
  -- 'link' = use that existing catalog item instead of creating a new one.
  dup_match_item_id bigint references public.menu_items (id) on delete set null,
  dup_match_type text check (dup_match_type in ('exact', 'similar')),
  resolution text not null default 'new' check (resolution in ('new', 'link')),
  -- True once the chef has renamed / changed attributes / picked a replacement.
  edited boolean not null default false,
  -- Set on Approve: the menu_items row this dish became (new) or was linked to. Also what makes a
  -- re-run of an interrupted Approve skip dishes it already created.
  resolved_item_id bigint references public.menu_items (id) on delete set null,
  created_at timestamptz not null default now(),
  check (resolution <> 'link' or dup_match_item_id is not null)
);

create index ai_menu_draft_dishes_run_id_idx on public.ai_menu_draft_dishes (run_id);
-- No two draft dishes in one run with the same name in the same category (case/space-insensitive).
create unique index ai_menu_draft_dishes_run_cat_name_uq
  on public.ai_menu_draft_dishes (run_id, category_code, lower(btrim(name)));

-- ------------------------------------------------------------------
-- 3. The draft menu itself: one row per slot per day per section.
-- ------------------------------------------------------------------
create table public.ai_menu_draft_picks (
  id bigint generated by default as identity primary key,
  run_id bigint not null references public.ai_menu_runs (id) on delete cascade,
  section_code text not null check (section_code in ('DAYCARE', 'KG_LP', 'MS_UP', 'STAFF')),
  menu_date date not null,
  weekday text not null,
  category_code text not null,
  slot_index smallint not null check (slot_index >= 0),
  -- An AI dish, OR a real catalog item (unchanged categories such as Milk / Fruit Bar, and dishes
  -- the chef picked from the catalog). Both null = an empty slot, which blocks Approve.
  draft_dish_id bigint references public.ai_menu_draft_dishes (id) on delete set null,
  item_id bigint references public.menu_items (id) on delete set null,
  -- Where a shared pick comes from, for the read-only cells: 'KG_LP' / 'MS_UP' for the coupled
  -- Lunch Main / Starch, 'DAYCARE' / 'KG_LP' / 'MS_UP' for Staff Main and Staff Breakfast shares.
  source_section_code text check (source_section_code in ('DAYCARE', 'KG_LP', 'MS_UP')),
  check (draft_dish_id is null or item_id is null),
  unique (run_id, section_code, menu_date, category_code, slot_index)
);

create index ai_menu_draft_picks_run_id_idx on public.ai_menu_draft_picks (run_id);
create index ai_menu_draft_picks_draft_dish_id_idx on public.ai_menu_draft_picks (draft_dish_id);

-- ------------------------------------------------------------------
-- 4. AI tag on the real Dish Catalog.
-- ------------------------------------------------------------------
alter table public.menu_items
  add column if not exists is_ai_generated boolean not null default false,
  add column if not exists ai_menu_run_id bigint references public.ai_menu_runs (id) on delete set null;

comment on column public.menu_items.is_ai_generated is
  'True for dishes invented by the AI Menu Generator and created on Approve. Never set for linked existing items.';
comment on column public.menu_items.ai_menu_run_id is
  'The ai_menu_runs row whose Approve created this item.';

create index if not exists menu_items_is_ai_generated_idx
  on public.menu_items (is_ai_generated) where is_ai_generated;

-- ------------------------------------------------------------------
-- 5. RLS: same blanket authenticated policy as every other table (see CLAUDE.md's RLS gotcha).
-- ------------------------------------------------------------------
alter table public.ai_menu_runs enable row level security;
alter table public.ai_menu_draft_dishes enable row level security;
alter table public.ai_menu_draft_picks enable row level security;

create policy "Allow authenticated full access" on public.ai_menu_runs
  for all to authenticated using (true) with check (true);
create policy "Allow authenticated full access" on public.ai_menu_draft_dishes
  for all to authenticated using (true) with check (true);
create policy "Allow authenticated full access" on public.ai_menu_draft_picks
  for all to authenticated using (true) with check (true);

commit;

notify pgrst, 'reload schema';
