-- Recipe on Fire pivot (Phase A): the chef rejected the 3D parametric tray/dough render in favor
-- of real, AI-generated reference photos used as draggable 2D sprites. This is the small,
-- chef-managed catalog of "Dough Shape" reference material that pivot depends on -- round ball,
-- baguette, mini baguette, ciabatta, extensible to more later -- each with its own real-world
-- size (so a sprite draws to scale against a tray's own real dimensions), a per-unit weight (so
-- placed-unit-count can be reconciled against a recipe's net weight -- replaces the old
-- fill-height/rise-based math, which had no visual left to drive it once the 3D render was
-- dropped), and a small SET of reference photos per stage (raw/baked/cut), not just one -- three
-- variations per stage, so a tray with many placed units of the same shape doesn't look like a
-- stamped-out repeating pattern, which would read as fake in a different way than the 3D render
-- did.
create table public.dough_shapes (
  id bigint generated by default as identity primary key,
  name text not null unique,
  -- Per-unit weight in grams -- e.g. one "Round Ball" placed on the tray represents this many
  -- grams of dough. Drives the new placed-count-vs-recipe-net-weight reconciliation.
  unit_weight_grams numeric not null,
  -- Rough real-world size in cm (diameter for a round shape, length for an elongated one like a
  -- baguette) -- purely for drawing the sprite to scale against the tray's own real dimensions on
  -- the 2D canvas; not a precise engineering dimension the way Material dims are.
  size_cm numeric not null,
  created_at timestamptz not null default now()
);

-- One row per (shape, stage, variation) -- e.g. "Round Ball" x "raw" x variation 0/1/2. A child
-- table rather than fixed columns on dough_shapes itself specifically because the variation COUNT
-- is expected to grow/change over time (3 to start, per the chef's own request) without a schema
-- change every time it does.
create table public.dough_shape_photos (
  id bigint generated by default as identity primary key,
  dough_shape_id bigint not null references public.dough_shapes (id) on delete cascade,
  stage text not null check (stage in ('raw', 'baked', 'cut')),
  variation_index integer not null default 0,
  photo_path text not null,
  created_at timestamptz not null default now(),
  unique (dough_shape_id, stage, variation_index)
);

create index dough_shape_photos_shape_id_idx on public.dough_shape_photos (dough_shape_id);

alter table public.dough_shapes enable row level security;
alter table public.dough_shape_photos enable row level security;

-- Same blanket "any authenticated session" policy every other table in this app uses (see
-- CLAUDE.md's RLS gotcha) -- single-chef-team desktop tool, authentication itself is the access
-- boundary, not row ownership.
create policy "Allow authenticated full access" on public.dough_shapes
  for all to authenticated using (true) with check (true);
create policy "Allow authenticated full access" on public.dough_shape_photos
  for all to authenticated using (true) with check (true);

-- Storage: private bucket + RLS policy, same shape as recipe-photos/material-photos/
-- generated-recipe-photos -- public=false, no bucket-level size/mime limit (enforced app-side),
-- one blanket authenticated-role policy scoped to this bucket_id.
insert into storage.buckets (id, name, public) values ('dough-shape-photos', 'dough-shape-photos', false);

create policy "Authenticated full access to dough shape photos" on storage.objects
  for all to authenticated
  using (bucket_id = 'dough-shape-photos')
  with check (bucket_id = 'dough-shape-photos');
