-- Recipe Generator: AI-generated, ~100g-reference recipes for dishes pulled from an uploaded
-- menu file (AM Snack / PM Snack / Soup / Appetizers / Main Course dishes only -- see
-- lib/recipeGenerator.js's category matching). Mirrors recipes/recipe_processes/
-- recipe_ingredients structurally (so Recipe Calculator's export/scaling code -- already
-- generic over {recipe, processes} -- needs zero new branching to treat this as a third
-- source), with two deliberate differences from that schema:
--
--   1. generated_recipe_ingredients has NO ingredient_id column at all (not just nullable --
--      structurally absent), since these ingredients must NEVER be linked to the ingredients/
--      extracted_ingredients catalogs, even after the recipe is permanently confirmed. This
--      mirrors Recipe Calculator's own inline "throwaway free text" ingredient rows
--      ({name, quantity, unit, method}, no FK), not Recipe Book/Extractor's catalog-aware rows.
--
--   2. generated_recipes carries a draft/confirmed lifecycle (status, code nullable until
--      confirmed, confirmed_at) that recipes/extracted_recipes don't have -- an RG- code is
--      only assigned when a chef confirms a reviewed draft (see nextGeneratedRecipeCode in
--      main.js), mirroring the existing "TTY-/EX- code assigned after saving" placeholder
--      pattern, just gated on a second explicit action instead of the first save.
--
-- No recipe_process_wastes equivalent -- waste % is a real-batch-production concept a chef
-- enters by hand later; meaningless for an AI-guessed 100g reference recipe. No material_id/
-- material_fill_weight_grams on generated_recipe_processes for the same reason (a mold/tray
-- fill weight is a real-batch concept). No photo columns -- these recipes are never
-- photographed; Recipe Calculator's photoModel:'single' path already no-ops cleanly when
-- photo_path is absent.

create table public.generated_recipes (
  id bigint generated by default as identity primary key,
  code text unique,
  status text not null default 'draft' check (status in ('draft', 'confirmed')),
  name text not null,
  category text,
  quantity_produced text,
  portion_weight_grams numeric,
  country_origin text,
  yield_notes text,
  date_created date,
  presentation_serving text,
  comment text,
  checked_by text,
  prepared_by text,
  -- Traceability back to the menu upload this recipe was generated from (requirement 6) --
  -- source_menu_label is the uploaded file's own name (e.g. "KG-LP_Menu_Sept.xlsx"),
  -- source_dish_name is the exact dish text from the menu row at generation time (kept even if
  -- she later edits `name` during review, so the link back to the source row never breaks).
  source_menu_label text not null,
  source_dish_name text not null,
  created_at timestamptz not null default now(),
  confirmed_at timestamptz
);

create index generated_recipes_status_idx on public.generated_recipes (status);

create table public.generated_recipe_processes (
  id bigint generated by default as identity primary key,
  generated_recipe_id bigint not null references public.generated_recipes (id) on delete cascade,
  name text not null,
  method text,
  sort_order integer not null default 0
);

create index generated_recipe_processes_recipe_id_idx on public.generated_recipe_processes (generated_recipe_id);

create table public.generated_recipe_ingredients (
  id bigint generated by default as identity primary key,
  process_id bigint not null references public.generated_recipe_processes (id) on delete cascade,
  -- Deliberately no ingredient_id column -- see the file-level comment above. Free text only,
  -- forever, even after confirmation.
  name text not null,
  quantity numeric,
  unit text,
  method text,
  sort_order integer not null default 0
);

create index generated_recipe_ingredients_process_id_idx on public.generated_recipe_ingredients (process_id);

alter table public.generated_recipes enable row level security;
alter table public.generated_recipe_processes enable row level security;
alter table public.generated_recipe_ingredients enable row level security;

-- Same blanket "any authenticated session" policy every other table in this app uses (see
-- CLAUDE.md's RLS gotcha) -- this is a single-chef-team desktop tool with no per-user data
-- partitioning, so authentication itself (not row ownership) is the access boundary.
create policy "Allow authenticated full access" on public.generated_recipes
  for all to authenticated using (true) with check (true);
create policy "Allow authenticated full access" on public.generated_recipe_processes
  for all to authenticated using (true) with check (true);
create policy "Allow authenticated full access" on public.generated_recipe_ingredients
  for all to authenticated using (true) with check (true);
