-- Recipe Generator parity additions: Waste % per process and a single reference photo, matching
-- Recipe Book/Extractor's existing process-card feature set (Material/Tray deliberately excluded
-- -- real-batch production equipment, meaningless for a 100g reference recipe, confirmed with the
-- chef). Both additions apply at the draft stage and carry through confirmation unchanged, since
-- save-generated-recipe already does a full wholesale replace of processes/ingredients (and now
-- wastes) from the submitted payload on every save, draft or confirm.

alter table public.generated_recipes add column photo_path text;

create table public.generated_recipe_process_wastes (
  id bigint generated by default as identity primary key,
  process_id bigint not null references public.generated_recipe_processes (id) on delete cascade,
  waste_type_id bigint not null references public.waste_types (id),
  percent numeric not null default 0,
  sort_order integer not null default 0
);

create index generated_recipe_process_wastes_process_id_idx on public.generated_recipe_process_wastes (process_id);

alter table public.generated_recipe_process_wastes enable row level security;
create policy "Allow authenticated full access" on public.generated_recipe_process_wastes
  for all to authenticated using (true) with check (true);

-- Storage: private bucket + RLS policy, same shape as recipe-photos/extracted-recipe-photos/
-- material-photos (inspected directly via pg_policies/storage.buckets before writing this --
-- public=false, no bucket-level size/mime limit (enforced app-side), one blanket
-- authenticated-role policy scoped to this bucket_id).
insert into storage.buckets (id, name, public) values ('generated-recipe-photos', 'generated-recipe-photos', false);

create policy "Authenticated full access to generated recipe photos" on storage.objects
  for all to authenticated
  using (bucket_id = 'generated-recipe-photos')
  with check (bucket_id = 'generated-recipe-photos');

-- Cleanup of the throwaway inspection table from the prior migration (20260911140100/140200) --
-- never meant to be permanent, its job (mirroring the existing bucket/policy shape above) is done.
drop table if exists public._storage_inspect;
